#!/bin/python

import json
import os

end_list = []

with open(os.path.expandvars("$HOME/.cache/wal/colors.json")) as file:
    stock = json.load(file)


def is_dark(color):
    rgb = int(color[1:], 16)
    # convert rrggbb to decimal
    r = (rgb >> 16) & 0xFF
    g = (rgb >> 8) & 0xFF
    b = (rgb >> 0) & 0xFF

    luma = 0.2126 * r + 0.7152 * g + 0.0722 * b

    return luma < 128


k1 = stock["colors"]["color0"]
k2 = stock["colors"]["color1"]
k3 = stock["colors"]["color2"]
k4 = stock["colors"]["color3"]
k5 = stock["colors"]["color4"]
k6 = stock["colors"]["color5"]
k7 = stock["colors"]["color6"]
k8 = stock["colors"]["color7"]
background = stock["special"]["background"]
foreground = stock["special"]["foreground"]


font_primary_color = foreground
font_secondary_color = k7 if is_dark(background) else k2
tag_selected_bg_color = k7 if is_dark(background) else k2
tag_selected_fg_color = background if is_dark(tag_selected_bg_color) else "#000000"


list1 = [
    "dwm.normfgcolor: ",
    "dwm.titlenormfgcolor: ",
    "dwm.tagsnormfgcolor: ",
    "dwm.urgfgcolor: ",
]

list2 = [
    "dwm.normbgcolor: ",
    "dwm.titlenormbgcolor: ",
    "dwm.tagsnormbgcolor: ",
    "dwm.hidnormbgcolor: ",
    "dwm.hidselbgcolor: ",
    "dwm.urgbgcolor: ",
]

list3 = [
    "dwm.normbordercolor: ",
    "dwm.titlenormbordercolor: ",
    "dwm.tagsnormbordercolor: ",
]

list4 = [
    "dwm.normfloatcolor: ",
    "dwm.titlenormfloatcolor: ",
    "dwm.tagsnormfloatcolor: ",
    "dwm.urgfloatcolor: ",
]

list5 = ["dwm.selfgcolor: "]

list6 = [
    "dwm.selbgcolor: ",
    "dwm.selfloatcolor: ",
    "dwm.titleselbgcolor: ",
    "dwm.titleselbordercolor: ",
    "dwm.titleselfloatcolor: ",
    "dwm.tagsselbgcolor: ",
    "dwm.tagsselbordercolor: ",
    "dwm.tagsselfloatcolor: ",
    "dwm.hidnormfgcolor: ",
]

list7 = ["dwm.hidselfgcolor: "]

list8 = ["dwm.urgbordercolor: ", "dwm.selbordercolor: "]

list9 = ["dwm.tagsselfgcolor: "]

for event in list1:
    string = str(event) + str(foreground)
    end_list.append(string)

for event in list2:
    string = str(event) + str(k2)
    end_list.append(string)

for event in list3:
    string = str(event) + str(k3)
    end_list.append(string)

for event in list4:
    string = str(event) + str(k4)
    end_list.append(string)

for event in list5:
    string = str(event) + str(k5)
    end_list.append(string)

for event in list6:
    string = str(event) + str(tag_selected_bg_color)
    end_list.append(string)

for event in list7:
    string = str(event) + str(k7)
    end_list.append(string)

for event in list8:
    string = str(event) + str(k8)
    end_list.append(string)

for event in list9:
    string = str(event) + str(tag_selected_fg_color)
    end_list.append(string)

end_list.append("dwm.titleselfgcolor: " + font_secondary_color)


follow_theme = [
    "dwm.normbgcolor",
    "dwm.titlenormbgcolor",
    "dwm.tagsnormbgcolor",
    "dwm.hidnormbgcolor",
    "dwm.hidselbgcolor",
    "dwm.urgbgcolor",
    "dwm.normbordercolor",
    "dwm.titlenormbordercolor",
    "dwm.tagsnormbordercolor",
    "dwm.titleselbgcolor",
]

for follow_theme_item in follow_theme:
    end_list.append(f"{follow_theme_item}: {background}")

for i in range(1, 9):
    exec(f'end_list.append("k{i}:' + eval(f"k{i}") + '")')

file = open(os.path.expandvars("$HOME/.Xresources"), "w")

for end_str in end_list:
    file.write(str(end_str) + "\n")

file.close()
